### ISSUE TITLE
Update basic example to include at 3+ HUCs (instead of only 1)

### ISSUE THREAD

**Issue by cgmorton** [usbr/et-demands#18]
I think it would make it a little more clear what is happening at each state of the prep and within the model if there were multiple ET cells that were being modeled.

**Comment by cgmorton** [comment]
It might be neat to only have to stations though to show how multiple cells can share a station.

**Comment by cpearson1** [comment]
Two new examples were added to the examples folder: huc8 and gridmet
Each example analyzes multiple zones using multiple weather stations. The huc8 examples showcases multiple cells sharing the same station.
