### ISSUE TITLE
etdemands_zonal_stats.py: 'zone_crop_poly' referenced before assignment

### ISSUE THREAD

**Issue by cpearson1** [usbr/et-demands#28]
The follow error occurs when:
soil_crop_mask_flag = False
save_crop_mask_flag = False
It does not occur when the mask variables are set to True.

![image](https://user-images.githubusercontent.com/14983120/51287039-8b142a00-19aa-11e9-8dac-a7e3345d520d.png)

**Comment by cgmorton** [comment]
I committed a quick fix that I think will fix this but I haven't tested it yet.
