### ISSUE TITLE
Test huc8 example

### ISSUE THREAD

**Issue by cpearson1** [usbr/et-demands#30]
et-demands\examples\huc8

See huc_example.rst in docs folder. model_commands.txt contains additional example commands.
Note any issues or areas where the documentation needs help.

**Comment by danbroman** [comment]
`et_demands_zonal_stats.py`

Script appears to hang up, but if not, takes too long - run for several hours without finishing

**Comment by cpearson1** [comment]
I tested the et_demands_zonal_stats.py script today with the huc8 example. It successfully completed in ~45 minutes. The zonal stats calcs take time.
![image](https://user-images.githubusercontent.com/14983120/51928812-9bb1a080-23ab-11e9-82fd-a8661612ac99.png)
The logging.info() statement on Line 317 is not printing to screen. This may help the user recognize that the script is running correctly. 
![image](https://user-images.githubusercontent.com/14983120/51928898-d0255c80-23ab-11e9-9ef3-4b66004bc331.png)

**Comment by cgmorton** [comment]
In the email notification you had an image of the FID print line.  That would actually work but it is only printing on the 1000th FID value.  You could change the 1000 to 10 or 100, or switch to the line below and print for every FID.

Once you are happy with the basic approach, we can try to go in and speed up the clipping.

**Comment by cpearson1** [comment]
I edited my comment because I figured out what was happening with the modulus statement. 
For now I will print the Zone FID to the screen using a logging.info() statement.

The crop_fid_list will print to screen when the debug flag is turned on.
