### ISSUE TITLE
Test gridmet example

### ISSUE THREAD

**Issue by cpearson1** [usbr/et-demands#31]
et-demands\examples\gridmet

See gridmet_example.rst in docs folder. model_commands.txt contains additional example commands.
Note any issues or areas where the documentation needs help.

**Comment by danbroman** [comment]
gridmet_historical_XXX.csv files not provided with example. Some of the commands in the model_commands.txt file referred to the HUC8 example or example2 and were updated as needed. run_cet.py was missing from example folder and was added. 

Download scripts for CDL and soils work fine - I thought I had added a status bar for downloads and some file checking to avoid issues with incomplete downloads. This may have been lost in a merge - I'll look on my end if you could look on yours too.

**Comment by danbroman** [comment]
Looks like at least some of the gridmet climate data were in the HUC8 climate folder. I've moved them and trying to re-run now.

**Comment by danbroman** [comment]
`CellID: 457500
  IOError: RefET data file could not be read and may not exist
  climate\gridmet_historical_457500.csv`

Still missing met data

**Comment by danbroman** [comment]
Example tested and working
