### ISSUE TITLE
Remove or move DEM related prep scripts

### ISSUE THREAD

**Issue by cgmorton** [usbr/et-demands#5]
Per the readthedocs page (http://et-demands.readthedocs.io/en/latest/prep_tools.html#unused-scripts) the DEM related scripts are no longer needed and could be removed.  Initially it might be best to just move these to an "unused" or "deprecated" folder inside the "prep" folder.

The scripts that should be moved are download_dem_rasters.py, build_ag_dem_rasters.py, and merge_dem_rasters.py.

**Comment by cgmorton** [comment]
The *_arcpy.py script should probably also be moved to this same folder

**Comment by cpearson1** [comment]
legacy_scripts folder contains all "deprecated" *_arcpy.py and dem scripts.
