### ISSUE TITLE
messy code in "et-demands/static/CropCoefs_etr.txt"

### ISSUE THREAD

**Issue by OuyangWenyu** [usbr/et-demands#59]
In the "et-demands/static/CropCoefs_etr.txt",  there are a few messy codes in the 44th, 45th, and 47th rows ('CGDD Planting to FC', 'CGDD Planting to Terminate', and 'Comment'). This file is the template “CropCoefs_etr.txt" file and will be copied to an assigned directory.

And when running the command -- "python ../../et-demands/cropET/bin/run_cet.py -i huc_example_cet.ini -b ../../et-demands/cropET/bin/" in the "et-demands\examples\huc8\model_commands.txt", there are some errors as following:

`(etdemands) C:\Projects\git\et-demands\examples\huc8>python ../../et-demands/cropET/bin/run_cet.py -i huc_example_cet.ini -b ../../et-demands/cropET/bin/

Python Crop ET
Traceback (most recent call last):
  File "../../et-demands/cropET/bin/mod_crop_et.py", line 371, in <module>
    debug_flag=args.debug, mp_procs=args.multiprocessing)
  File "../../et-demands/cropET/bin/mod_crop_et.py", line 92, in main
    data.set_crop_coeffs()
  File "C:\Projects\git\et-demands\et-demands\cropET\bin\crop_et_data.py", line 1261, in set_crop_coeffs
    crop_coefficients.read_crop_coefs_txt(self)
  File "C:\Projects\git\et-demands\et-demands\cropET\bin\crop_coefficients.py", line 107, in read_crop_coefs_txt
    a = np.loadtxt(data.crop_coefs_path, delimiter = data.crop_coefs_delimiter, dtype = 'str')
  File "C:\Users\hust2\miniconda3\envs\etdemands\lib\site-packages\numpy\lib\npyio.py", line 1139, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "C:\Users\hust2\miniconda3\envs\etdemands\lib\site-packages\numpy\lib\npyio.py", line 1055, in read_data
    for i, line in enumerate(line_iter):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x97 in position 2969: illegal multibyte sequence`

**Comment by cpearson1** [comment]
ET Demands scripts utilize 'utf-8' encoding. The error message you posted appears to be using 'gbk' encoding.

You can check your python encoding via the the following:
![image](https://user-images.githubusercontent.com/14983120/94587231-1e50ca00-0237-11eb-8440-b50cbc851a67.png)

**Comment by OuyangWenyu** [comment]
Thanks! But mine is 'utf-8'. 

I think the original "CropCoefs.txt" file in the GitHub repo has some messy code:

![image](https://user-images.githubusercontent.com/10172837/94815667-ca75ea80-03c8-11eb-97c9-94792ba28f28.png)

the page source code:

![image](https://user-images.githubusercontent.com/10172837/94815840-fd1fe300-03c8-11eb-8d23-370dab15baa0.png)

**Comment by cpearson1** [comment]
I ran through the HUC8 example and am not able to reproduce your error. Opening the CropCoef_etr.txt file with a text editor (e.g. notepad++) or excel decodes the questionable characters (-, ') with no problems. 
![image](https://user-images.githubusercontent.com/14983120/94830927-ef665f80-03c0-11eb-8d34-e23bf7d427cf.png)


Can you try specifying 'bytes' encoding on in the np.loadtxt function (Line 107 of crop_coefficients.py)? This should be the default. 
a = np.loadtxt(data.crop_coefs_path, delimiter = data.crop_coefs_delimiter, dtype = 'str', encoding='bytes')

What version of numpy are you running?

**Comment by OuyangWenyu** [comment]
My version of NumPy is 1.19.1.
Still don't know why there are some messy codes in my downloaded file (I have recoded the file with different encoding systems, not work), but I have modified it manually as you showed me, and it works now.
Thank you!
